spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://spring_app_pg:5432/spring
    username: spring
    password: 1234
    driver-class-name: org.postgresql.Driver